Algoritmo "semnome"
// Calcule e apresente a área de um triângulo: Área
// = (base * altura) / 2
Var
area, base, altura: real

Inicio
// Descobrindo a base
escreva("Informe a base do triângulo:")
leia(base)

// Descobrindo a altura
escreva("Informe a altura do triângulo:")
leia(altura)

// Operando e Apresentando o Resultado ao usuário
area <- (base * altura)/2
escreva("A area do triangulo é:", area)

Fimalgoritmo