algoritmo "semnome"
// Solicite o nome e a idade de 4 pessoas e calcule
// a media das idades.

var
n1, n2, n3, n4, media: inteiro


inicio
escreva("Qual a idade do mais velho? ")
leia(n1)
escreva("Qual a idade do segundo mais velho? ")
leia(n2)
escreva("Qual a idade do terceiro mais velho? ")
leia(n3)
escreva("Qual a idade do mais novo? ")
leia(n4)
media <- (n1+n2+n3+n4)/4

escreva("A média da idades é: ", media)
fimalgoritmo
