Algoritmo "semnome"
// Gere 4 valores aleatórios e apresente os números
// e a soma total.
Var
n1, n2, n3, n4: inteiro


Inicio
n1 <- randi(100)
n2 <- randi(100)
n3 <- randi(100)
n4 <- randi(100)

escreval("o primeiro numero gerado foi", n1)
escreval("o segundo numero gerado foi", n2)
escreval("o terceiro numero gerado foi", n3)
escreval("o quarto numero gerado foi", n4)

escreva("a soma desses números resultam em: ", n1+n2+n3+n4)


Fimalgoritmo