algoritmo "Nome do Programa"
// Solicite dois valores, calcule a soma entre eles
// e apresente o resto da divisão por 3.
var
n1, n2: real

inicio
    escreva("Digite o primeiro número: ")
    leia(n1)
    escreva("Digite o segundo número: ")
    leia(n2)
    
    escreval("A soma de ", n1, " e ", n2, " é: ", n1 + n2)
    escreval("Dividido por 3 é: ", (n1 + n2)/3)
    escreval("E o resto da divisão é:", (n1+n2)%3)
fimalgoritmo